import { OptionNumber, OptionString } from "./Options.ts";

export type OrganizationDTO = {
  id: number;
  leader_id: number;
  name: OptionString;
  country: OptionString;
  state: OptionString;
  city: OptionString;
  zipcode: OptionString;
  street_address: OptionString;
  street_number: OptionString;
  street_extra: OptionString;
  district: OptionString;
  category: OptionString;
  phone_code: OptionString;
  phone: OptionString;
  cell_phone_code: OptionString;
  cell_phone: OptionString;
  website: OptionString;
  latitude: OptionNumber;
  longitude: OptionNumber;
  text: OptionString;
  cover_picture: OptionString;
  avatar: OptionString;
  leader_member_full_name: OptionString;
  leader_member_avatar: OptionString;
  sub_organizations_number: BigInt;
  terms_id: number;
  sub_organization_level_one: OptionString;
  sub_organization_level_two: OptionString;
  sub_organization_level_one_plural: OptionString;
  sub_organization_level_two_plural: OptionString;
  cell_singular: OptionString;
  cell_plural: OptionString;
  gender: OptionString;
  contribution_singular: OptionString;
  contribution_plural: OptionString;
  member_contributions: OptionString;
  expense_singular: OptionString;
  expense_plural: OptionString;
  super_cell_singular: OptionString;
  super_cell_plural: OptionString;
  super_cell_gender: OptionString;
  online_contribution: boolean | null;
  avatar_cloudinary: OptionString;
  cover_picture_cloudinary: OptionString;
  pay_management_status: OptionString;
  financial_management_status: OptionString;
  teaching_management_status: OptionString;
  contribution_types_count: BigInt;
};
